backend:
  name: git-gateway
  # name: test-repo
  branch: main # Branch to update (optional; defaults to master)
site_url: https://longmynd.netlify.app
media_folder: public/img
public_folder: /img
collections:
  - name: "mainPages"
    label: "Main Pages"
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: "{{title}}" # optional summary for a tree node, defaults to the inferred title field
    files:
      - label: "Home"
        name: "home"
        file: "content/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - {
              label: "Top Body",
              name: "topBody",
              widget: "markdown",
              media_library: { config: { max_file_size: 2000000 } },
            }
          - { label: "Body", name: "body", widget: "markdown", media_library: { config: { max_file_size: 2000000 } } }
      - label: "News"
        name: "news"
        file: "content/news/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Sites"
        name: "sites"
        file: "content/sites/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Other Clubs Sites"
            name: "otherClubsSites"
            widget: "list"
            fields:
              - {
                  label: "Club Name",
                  name: "clubName",
                  widget: "select",
                  options: ["South East Wales HGPC", "Malvern HGC", "North Wales HGPC"],
                }
              - { label: "Site Name", name: "siteName", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - {
                  label: "From",
                  name: "from",
                  widget: "select",
                  options:
                    [
                      "N",
                      "NNE",
                      "NE",
                      "ENE",
                      "E",
                      "ESE",
                      "SE",
                      "SSE",
                      "S",
                      "SSW",
                      "SW",
                      "WSW",
                      "W",
                      "WNW",
                      "NW",
                      "NNW",
                    ],
                }
              - {
                  label: "To",
                  name: "to",
                  widget: "select",
                  options:
                    [
                      "N",
                      "NNE",
                      "NE",
                      "ENE",
                      "E",
                      "ESE",
                      "SE",
                      "SSE",
                      "S",
                      "SSW",
                      "SW",
                      "WSW",
                      "W",
                      "WNW",
                      "NW",
                      "NNW",
                    ],
                }

  - label: "Sites"
    name: "sites"
    folder: "content/sites"
    create: true
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Published", name: "published", widget: "boolean", default: true, required: false }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["Open to all", "Open to club members", "Closed"],
          default: "Open to all",
        }
      - { label: "Sensitive", name: "sensitive", widget: "boolean", default: false, required: false }
      - { label: "Fee", name: "fee", widget: "string", required: false }
      - { label: "Required HG Rating", name: "hgRating", widget: "string" }
      - { label: "Required PG Rating", name: "pgRating", widget: "string" }
      - label: "Takes Wind Direction"
        name: "windDirection"
        widget: "list"
        summary: "{{fields.from}} - {{fields.to}}"
        fields:
          - {
              label: "From",
              name: "from",
              widget: "select",
              options:
                ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"],
            }
          - {
              label: "To",
              name: "to",
              widget: "select",
              options:
                ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"],
            }
      - label: "Location"
        name: "location"
        widget: "object"
        collapsed: true
        fields:
          - { label: "What three words", name: "what3words", widget: "string" }
          - {
              label: "Latitude & Longitude",
              name: "latlong",
              widget: "string",
              pattern: ['^((\-?|\+?)?\d+(\.\d+)?),\s*((\-?|\+?)?\d+(\.\d+)?)$', "Must be decimal lat/long"],
            }
          - { label: "Physical Maps", name: "physicalMaps", widget: "string" }
      - { label: "Introduction", name: "body", widget: "markdown", required: false }
      - {
          label: "Sensitivities",
          name: "sensitivities",
          widget: "list",
          required: false,
          fields: [{ label: "Sensitivity", name: "sensitivity", widget: "text" }],
        }
      - { label: "Access And Parking", name: "accessAndParking", widget: "markdown", required: false }
      - { label: "Launches And Landing", name: "launchesAndLanding", widget: "markdown", required: false }
      - { label: "Flying", name: "flying", widget: "markdown", required: false }
      - {
          label: "Weather Stations",
          name: "weatherStations",
          widget: "list",
          required: false,
          fields: [{ label: "Station", name: "station", widget: "text" }],
        }
      - { label: "Webcams", name: "webcams", widget: "markdown", required: false }
      - { label: "Local Attractions", name: "localAttractions", widget: "markdown", required: false }
      - {
          label: "Site Records",
          name: "siteRecords",
          widget: "list",
          required: false,
          fields: [{ label: "Record", name: "record", widget: "text" }],
        }
      - {
          label: "Main Image",
          name: "mainImage",
          widget: "image",
          required: false,
          media_library: { config: { max_file_size: 512 } },
        }
      - { label: "POI Image", name: "poiImage", widget: "image", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
  - label: "News"
    name: "news"
    folder: "content/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Weather"
    name: "weather"
    folder: "content/weather"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Safety"
    name: "safety"
    folder: "content/safety"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
