backend:
  name: git-gateway
  # name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Top Body", name: "topbody", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "News"
        name: "news"
        file: "content/news.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "Sites"
    name: "sites"
    folder: "content/sites"
    create: true
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["Open to all", "Open to club members", "Closed"],
          default: "Open to all",
        }
      - {
          label: "Sensitive",
          name: "sensitive",
          widget: "select",
          options: ["Sensitive", "Not Sensitive"],
          default: ["Not Sensitive"],
        }
      - { label: "HG Rating", name: "hgrating", widget: "string" }
      - { label: "PG Rating", name: "pgrating", widget: "string" }
      - label: "Takes Wind Direction"
        name: "windDirection"
        widget: "list"
        summary: "{{fields.from}} - {{fields.to}}"
        fields:
          - {
              label: "From",
              name: "from",
              widget: "select",
              options:
                ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"],
            }
          - {
              label: "To",
              name: "to",
              widget: "select",
              options:
                ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"],
            }
      - label: "Location"
        name: "location"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Grid Ref", name: "gridref", widget: "string" }
          - { label: "Latitude", name: "latitude", widget: "number", value_type: "float" }
          - { label: "longitude", name: "longitude", widget: "number", value_type: "float" }
          - { label: "Maps", name: "maps", widget: "string" }
      - { label: "Sensitivities", name: "sensitivities", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "News"
    name: "news"
    folder: "content/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Safety"
    name: "safety"
    folder: "content/safety"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
