backend:
  name: git-gateway
  # name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Top Body", name: "topbody", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "News"
        name: "news"
        file: "content/news.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "Sites"
    name: "sites"
    folder: "content/sites"
    create: true
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["Open", "Closed"], default: "Open" }
      - {
          label: "Sensitive",
          name: "sensitive",
          widget: "select",
          options: ["Sensitive", "Not Sensitive"],
          default: ["Not Sensitive"],
        }
      - {
          label: "Location",
          name: "location",
          widget: "object",
          fields:
            - { label: "Grid Ref", name: "gridref", widget: "string" }
            - { label: "LatLong", name: "latlong", widget: "map" }
        }
      - { label: "Sensitivities", name: "sensitivities", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "News"
    name: "news"
    folder: "content/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Safety"
    name: "safety"
    folder: "content/safety"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
